using UnityEngine;
using System.Collections.Generic;

namespace HuaweiService.analytic
{
    public class HAParamType
    {
        public const string STORENAME = "$StoreName";
        public const string BRAND = "$Brand";
        public const string CATEGORY = "$Category";
        public const string PRODUCTID = "$ProductId";
        public const string PRODUCTNAME = "$ProductName";
        public const string PRODUCTFEATURE = "$ProductFeature";
        public const string PRICE = "$Price";
        public const string QUANTITY = "$Quantity";
        public const string REVENUE = "$Revenue";
        public const string CURRNAME = "$CurrName";
        public const string PLACEID = "$PlaceId";
        public const string DESTINATION = "$Destination";
        public const string ENDDATE = "$EndDate";
        public const string BOOKINGDAYS = "$BookingDays";
        public const string PASSENGERSNUMBER = "$PassengersNumber";
        public const string BOOKINGROOMS = "$BookingRooms";
        public const string ORIGINATINGPLACE = "$OriginatingPlace";
        public const string BEGINDATE = "$BeginDate";
        public const string TRANSACTIONID = "$TransactionId";
        public const string CLASS = "$Class";
        public const string CLICKID = "$ClickId";
        public const string PROMOTIONNAME = "$PromotionName";
        public const string CONTENT = "$Content";
        public const string EXTENDPARAM = "$ExtendParam";
        public const string MATERIALNAME = "$MaterialName";
        public const string MATERIALSLOT = "$MaterialSlot";
        public const string MEDIUM = "$Medium";
        public const string SOURCE = "$Source";
        public const string KEYWORDS = "$Keywords";
        public const string OPTION = "$Option";
        public const string STEP = "$Step";
        public const string VIRTUALCURRNAME = "$VirtualCurrName";
        public const string VOUCHER = "$Voucher";
        public const string PLACE = "$Place";
        public const string SHIPPING = "$Shipping";
        public const string TAXFEE = "$TaxFee";
        public const string USERGROUPID = "$UserGroupId";
        public const string LEVELNAME = "$LevelName";
        public const string RESULT = "$Result";
        public const string ROLENAME = "$RoleName";
        public const string LEVELID = "$LevelId";
        public const string CHANNEL = "$Channel";
        public const string SCORE = "$Score";
        public const string SEARCHKEYWORDS = "$SearchKeywords";
        public const string CONTENTTYPE = "$ContentType";
        public const string ACHIEVEMENTID = "$AchievementId";
        public const string FLIGHTNO = "$FlightNo";
        public const string POSITIONID = "$PositionId";
        public const string PRODUCTLIST = "$ProductList";
        public const string ACOUNTTYPE = "$AcountType";
        public const string OCCURREDTIME = "$OccurredTime";
        public const string EVTRESULT = "$EvtResult";
        public const string PREVLEVEL = "$PrevLevel";
        public const string CURRVLEVEL = "$CurrvLevel";
        public const string VOUCHERS = "$Vouchers";
        public const string MATERIALSLOTTYPE = "$MaterialSlotType";
        public const string LISTID = "$ListId";
        public const string FILTERS = "$Filters";
        public const string SORTS = "$Sorts";
        public const string ORDERID = "$OrderId";
        public const string PAYTYPE = "$PayType";
        public const string REASON = "$Reason";
        public const string EXPIREDATE = "$ExpireDate";
        public const string VOUCHERTYPE = "$VoucherType";
        public const string SERVICETYPE = "$ServiceType";
        public const string DETAILS = "$Details";
        public const string COMMENTTYPE = "$CommentType";
        public const string REGISTMETHOD = "$RegistMethod";
        public const string DURATION = "$Duration";
        public const string LEVEL = "$Level";
        public const string PURCHASEENTRY = "$PurchaseEntry";
        public const string PROPS = "$Props";
        public const string ENTRY = "$Entry";
    }
}